# Regenerate local web fonts after adding Korean UI text. Fonts use the SIL OFL.
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$fontProjectRoot = Split-Path -Parent $PSScriptRoot
$fontWebRoot = Join-Path $fontProjectRoot 'web'
$fontAssetRoot = Join-Path $fontWebRoot 'assets/fonts'
$fontSourceText = (Get-ChildItem -LiteralPath $fontWebRoot -File |
    Where-Object Extension -In '.html', '.js', '.css' |
    ForEach-Object { Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8 }) -join "`n"
# Include calendar words generated by Intl as well as literal source characters.
$fontSourceText += -join ([char[]]@(0xC6D4, 0xD654, 0xC218, 0xBAA9, 0xAE08, 0xD1A0, 0xC77C))
$fontCharacters = -join ($fontSourceText.ToCharArray() | Sort-Object { [int]$_ } -Unique)
$fontEncodedText = [Uri]::EscapeDataString($fontCharacters)
$fontManifest = @(
    @{ Family = 'Gowun+Batang:wght@700'; Name = 'GowunBatang-Bold' },
    @{ Family = 'Gowun+Dodum'; Name = 'GowunDodum-Regular' }
)
foreach ($fontEntry in $fontManifest) {
    $fontCssUri = 'https://fonts.googleapis.com/css2?family=' + $fontEntry.Family + '&text=' + $fontEncodedText
    $fontCss = (Invoke-WebRequest -Uri $fontCssUri -UseBasicParsing).Content
    $fontAssetUri = [Uri]([regex]::Match($fontCss, 'url\(([^)]+)\)').Groups[1].Value)
    if ($fontAssetUri.Scheme -ne 'https' -or $fontAssetUri.Host -ne 'fonts.gstatic.com') {
        throw 'Unexpected font download URL.'
    }
    $fontDestination = Join-Path $fontAssetRoot ($fontEntry.Name + '-web.ttf')
    Invoke-WebRequest -Uri $fontAssetUri.AbsoluteUri -OutFile $fontDestination
    Get-Item -LiteralPath $fontDestination | Select-Object Name, Length
}
